# Select image from https://hub.docker.com/_/php/
image: php:5.6

# Select what we should cache
cache:
  paths:
  - vendor/
  - $HOME/.composer/cache

before_script:
# Install git and redis, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git unzip -yqq


# Install composer
- curl -sS https://getcomposer.org/installer | php
# Install all project dependencies
- php composer.phar selfupdate
- php composer.phar global require "fxp/composer-asset-plugin:^1.2.0"
- php composer.phar install

services:
- redis:3.2

test:redis:
  script:
  - vendor/bin/codecept run

