# Select image from https://hub.docker.com/_/php/

# Select what we should cache
cache:
  paths:
  - vendor/
  - /cache/composer

before_script:
# Install git and redis, the php image doesn't have installed
  - apt-get update -yqq
  - apt-get install git unzip -yqq


# Install composer
  - curl -sS https://getcomposer.org/installer | php
# Force cache dir
  - php composer.phar config cache-dir /cache/composer
# Update composer
  - php composer.phar selfupdate
# Install global dependencies
  - php composer.phar global require "fxp/composer-asset-plugin:^1.2.0"
# Install all project dependencies
  - php composer.phar install

variables:
  GITLAB_CI: "1"

services:
  - redis:3.2

test:7.1:
  image: php:7.1
  script:
  - vendor/bin/codecept run

test:7.2:
  image: php:7.2
  script:
  - vendor/bin/codecept run
